# Reference Material for Working with NumPy

***
- [Initializing](#Initializing)
- [Properties](#Properties)
- [Basic Functions](#Basic-Functions)
- [Mathmatics](#Mathmatics)
- [Iterate](#Iterate)
- [Reshaping](#Reshaping)
- [Index With Boolean](#Index-With-Boolean)
- [Special Considerations](#Special-Considerations)

In [1]:
import numpy as np

In [3]:
#Confusion
a = np.array([[1,2],[3,4],[5,6]], dtype = complex)
print(a)
a.dot(b)  #matrix product

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

# Initalizing

In [27]:
npArray = np.array([5,6,9])                              #1D Array
np2Array = np.array([[1,2,3],[4,5,6],[7,8,9]])           #2D Array
npfArray = np.array([2,4,6,7], dtype = np.float64)       #set data type
np0Array = np.zeros((3,4))                               #double zeros of shape
np1Array = np.ones((3,4))                                #double ones of shape
npRange = np.arange(1,5)                                 #array of 1,2,3,4
npStepR = np.arange(1,5,2)                               #arange but every 2nd num
npLin = np.arange(1,5,10)                                #10 even spaced num 1-5

# Properties

In [ ]:
npArray.ndim                                             #diminsionality
npArray.itemsize                                         #byte size of each element
npArray.dtype                                            #data type of element
npArray.size                                             #number of elements
npArray.shape                                            #number of rows and columns

# Basic Functions

In [28]:
npArray[0]                                               #get a value
npArray[0:2]                                             #returns elements 0 and 1
npArray[-1]                                              #returns last element
np2Array[1,2]                                            #element at row 1 column 2
np2Array[0:2,2]                                          #e.. at rows 0 & 1 at col 2
np2Array[-1,0:2]                                         #last row, cols 1 and 2
np2Array[:,1:3]                                          #all at columns 1 and 2

array([[2, 3],
       [5, 6],
       [8, 9]])

# Mathmatics

In [ ]:
npArray.min()
npArray.max()
npArray.sum()
np2Array.sum(axis = 0)                                   #sum of columns seperately
np2Array.sum(axis = 1)                                   #sum of rows
np.sqrt(npArray)                                         #square root of each element
np.std(npArray)                                          #standard deviation of array

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a+b                                                      #add a[0]+b[0] etc.
a-b
a*b
a/b
a.dot(b)                                                 #matrix product

# Iterate

In [29]:
for row in npArray:
    #print(row)
    pass
    
for cell in np2Array.flat:
    #print(cell)
    pass
  
print("C order:")
for x in np.nditer(np2Array,order='C'):                  #C order, row by row
    print(x)
print("Fortran:")
for x in np.nditer(np2Array, order='F'):                 #Fortran, col by col
    print(x)
print("Fortran with flags:")
for x in np.nditer(np2Array, order='F', flags=['external_loop']):
    print(x)
    
for x in np.nditer(np2Array, op_flags=['readwrite']):    #squared each value 
    x[...]=x*x                                           #and modify original array
    
a = np.arange(1,17).reshape(2,8)
b = np.arange(3,150,20).reshape(1,8)
for x,y in np.nditer([a,b]):                             #must have same shape
    print(x,y)                                           #or one D has to be 1

C order:
1
2
3
4
5
6
7
8
9
Fortran:
1
4
7
2
5
8
3
6
9
Fortran with flags:
[1 4 7]
[2 5 8]
[3 6 9]
1 3
2 23
3 43
4 63
5 83
6 103
7 123
8 143
9 3
10 23
11 43
12 63
13 83
14 103
15 123
16 143


# Reshaping

In [ ]:
np2Array.reshape(9,1)                                    #adjust rows and columns
np2Array.ravel()                                         #flattens an array to 1D
np2Array.flatten()                                       #ravel but Always returns copy

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.vstack((a,b))                                         #like concat for columns
np.hstack((a,b))                                         #and for rows
np.hsplit(a,3)                                           #split into 3 equal array
np.vsplit(a,2)                                           #and for rows

# Index With Boolean

In [11]:
a = np.arange(12).reshape(3,4)
b = a > 4                                                 #check if each elem is >4
a[b]                                                      #return elem in a is b is True
a[b] = -1                                                 #replace all elem > 4 with -1

array([ 5,  6,  7,  8,  9, 10, 11])

# Special Considerations

[return to top](#Reference-Material-for-Working-with-NumPy)